apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: child-app-1
spec:
  project: argocd
  source:
    repoURL: https://github.com/valipashask26/argocd-learning-2.git
    targetRevision: master
    path: apps/child-app-1
  destination:
    server: https://kubernetes.default.svc
    namespace: abcd-1
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
